version: '2'

services:
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
       POSTGRES_DB: ngo_db
       POSTGRES_USER: admin
       POSTGRES_PASSWORD: mysupersecretpw
       POSTGRES_PORT: 5432
    ports:
      - 5432:5432